# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sprynthesis
tagline:          "Writings by <a href='http://twitter.com/sprynmr'>Bob Spryn</a>, an iOS Engineer at <a href='http://www.lohilabs.com'>Lohi Labs</a> and <a href='http://www.threecentsapp.com'>Three Cents</a>"
url:              http://www.sprynthesis.com/
port:             4000
paginate:         1
baseurl:          ""
host:             0.0.0.0
author:
  name:           Bob Spryn
  url:            https://twitter.com/sprynmr
  email:          bobspryn@gmail.com

# Custom vars
github:
  repo:           https://github.com/sprynmr/sprynmr.github.io
subtitle: "Writings by Bob Spryn, an iOS Engineer"