# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sprynthesis
tagline:          "Writings by Bob Spryn, an iOS Engineer"
url:              http://localhost:4000/
port:             4000
paginate:         1
baseurl:          ""
host:             0.0.0.0
author:
  name:           Bob Spryn
  url:            https://twitter.com/sprynmr
  email:          bobspryn@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/sprynmr/sprynmr.github.io
